- name: "Uninstall Mirror Appliance"
  gather_facts: yes
  hosts: all
  tags:
    - quay
  tasks:
    - name: uninstall_mirror_appliance
      import_role:
        name: mirror_appliance
        tasks_from: uninstall
