---
systemd_unit_dir: "{{ '/etc/systemd/system' if ansible_user_uid == 0 else '$HOME/.config/systemd/user' }}"
systemd_scope: "{{ 'system' if ansible_user_uid == 0 else 'user' }}"
auto_approve: "false"
