- name: Generate secrets for Quay config.yaml
  set_fact:
    secret_key: "{{ lookup('community.general.random_string', length=48, base64=True) }}"
    database_secret_key: "{{ lookup('community.general.random_string', length=48, base64=True) }}"
    redis_password: "{{ lookup('community.general.random_string', length=24, special=False) }}"
